### ISSUE TITLE
Meta description in Google search results missing for German & English versions

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#18]
Observed behavior:
Meta description still missing for both hypofriend.de and hypofriend.com

![image](https://cloud.githubusercontent.com/assets/28759801/26300848/a1baac2c-3edf-11e7-944c-bdfb7a586bb9.png)

![image](https://cloud.githubusercontent.com/assets/28759801/26301712/460c1624-3ee2-11e7-90a9-3a6b485151a8.png)

Expected behavior:
Meta description should be added to html file

English:
"Use HypoFriend to refinance your mortgage to a lower interest rate and save €23,000 on average.

German:
"Nutze HypoFriend, um deine Hypothek auf einen niedrigeren Zinssatz zu refinanzieren. Das spart durchschnittlich €23.000 Zinsen."

**Comment by bstarr322** [comment]
Fixed

**Comment by bstarr322** [comment]
fixed, pls use https://chrome.google.com/webstore/detail/seo-website-analysis/hlngmmdolgbdnnimbmblfhhndibdipaf/related?hl=en

**Comment by hypostef** [comment]
This issue is still not fixed. I have re-opened it.

Just google: hypofriend.com and you will see the problem
