### ISSUE TITLE
<h1> headings not assigned

### ISSUE THREAD

**Issue by hypostef** [HypoFriend/HypoFriend#20]
Observed behavior:
![image](https://cloud.githubusercontent.com/assets/28759801/26301403/69130a3e-3ee1-11e7-8b7a-4ada66edd76d.png)

Expected behavior:
Please convert the following content into h1 headings:

English:

- Save on your mortgage by comparing the best refinancing options.
- Most home owners are overpaying on their existing mortgages.
- Refinance at historically low interest rates
- Free advice from HypoFriend mortgage experts

German:

- Hypothek refinanzieren und kräftig Zinsen sparen
- Die meisten Darlehennehmer zahlen zu viel für ihre Baufinanzierungen.
- Refinanziere zu den historisch niedrigen Hypothekenzinsen
- Kostenlose Beratung von HypoFriends Darlehenexperten

**Comment by bstarr322** [comment]
changed main domain as .com and redirect it to .de. so observing SEO factors

**Comment by bstarr322** [comment]
Added

**Comment by bstarr322** [comment]
fixed, pls use https://chrome.google.com/webstore/detail/seo-website-analysis/hlngmmdolgbdnnimbmblfhhndibdipaf/related?hl=en

**Comment by hypostef** [comment]
This is still not fixed! 

No headers have been defined yet.

**Comment by bstarr322** [comment]
toolbox.seositecheckup.com is not correct even the site includes headers, maybe because of free version?
pls see the following images:
![image](https://user-images.githubusercontent.com/15979250/27438723-db57433a-576e-11e7-98f9-a84cb690ccfa.png)

![image](https://user-images.githubusercontent.com/15979250/27438652-a126be48-576e-11e7-99e4-a3140b9b13b2.png)

![image](https://user-images.githubusercontent.com/15979250/27438658-a4a61fc8-576e-11e7-9925-7ed3f71df630.png)

![image](https://user-images.githubusercontent.com/15979250/27438660-a720ece2-576e-11e7-8e92-c21161691feb.png)

pls use https://chrome.google.com/webstore/detail/seo-website-analysis/hlngmmdolgbdnnimbmblfhhndibdipaf/related?hl=en

**Comment by nickdotmulder** [comment]
Ok - believe you. Thanks for the clear explanation!
