### ISSUE TITLE
Fix the UI for the information tip

### ISSUE THREAD

**Issue by nickdotmulder** [HypoFriend/HypoFriend#95]
Observed:
<img width="285" alt="screen shot 2017-06-24 at 9 57 26 am" src="https://user-images.githubusercontent.com/2698549/27506888-9224b32c-58c3-11e7-942d-8cfb8a2ecb4a.png">

Expected:
<img width="314" alt="screen shot 2017-06-24 at 9 58 03 am" src="https://user-images.githubusercontent.com/2698549/27506895-a207894a-58c3-11e7-847f-f4c3b26310c9.png">

**Comment by bstarr322** [comment]
Fixed

**Comment by nickdotmulder** [comment]
Not fixed;

<img width="678" alt="screen shot 2017-06-24 at 7 51 20 pm" src="https://user-images.githubusercontent.com/2698549/27510687-95f630fe-5916-11e7-9374-c9123f7495fe.png">

**Comment by bstarr322** [comment]
Fixed

**Comment by nickdotmulder** [comment]
This is not fixed the i is not the right font, the circle is not round, the font isn't the right color?

![image](https://user-images.githubusercontent.com/2698549/27536392-397db892-5a6f-11e7-96c4-2633898f0d90.png)

**Comment by nickdotmulder** [comment]
This is what I see: 

<img width="33" alt="screen shot 2017-06-26 at 12 59 31 pm" src="https://user-images.githubusercontent.com/2698549/27536419-5bd54f36-5a6f-11e7-8cfb-6863605e2fd2.png">
